spring:

  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: create  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MySQLDialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/healpet?userSSL=false&characterEncoding=UTF-8
    username: root
    password: 1234

server:
  error:
    whitelabel:
      enabled: false

  servlet:
    encoding:
      charset: UTF-8
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: "*"